#!/bin/bash

if [[ -n "$TRACE" ]]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi

dirname="${0%/*}"
export PATH="${dirname}/node_modules/.bin":$PATH

# shellcheck source=./unifi_sh_env
[[ -f "${dirname}/unifi_sh_env" ]] && source "${dirname}/unifi_sh_env"
# shellcheck source=./unifi_sh_api
source "${dirname}/unifi_sh_api"

cmd="$1"
shift

unifi_login >/dev/null

"unifi_$cmd" "$@" | json data

unifi_logout >/dev/null

rm -rf "${cookie:?}"
